server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lt_commerce?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapping/*.xml
logging:
  level:
    com.alon.mapper.dao:  debug